### ISSUE TITLE
Why do we fail kafka consumer if the previous version for the subject not found?

### ISSUE THREAD

**Issue by varunkamra** [flix-tech/schema-registry-php-client#72]
Kafka schema registry allows a user to permanently/softly delete a subject version without any issues. Why does this client fail consumption of message if version 1 was not found?

Version tested on: 7.5.0

**Comment by varunkamra** [comment]
@tPl0ch

**Comment by tPl0ch** [comment]
@varunkamra - just because the API of the schema registry allows it does not mean it's a good idea. Schema versions are part of the message protocol and encoded in the message. If you delete a Schema version for which a message has already been published, that message is going to fail during de-serialization.
